#!/bin/bash

if [[ $# -eq 0 ]]; then
    echo -e "You must provide at least one Python version.\n e.g. sh install-python 3.7.9"
    exit 2
fi

echo "Configuring packages..."
sudo yum install -q -y gcc make zlib-devel bzip2-devel openssl-devel ncurses-devel \
readline-devel tk-devel gdbm-devel db4-devel libpcap-devel xz-devel libffi-devel \
libuuid-devel sqlite-devel expat-devel libjpeg-devel libpng-devel libtiff-devel \
freetype-devel


cd /tmp

for VER do
    if [[ $VER == *"a"* ]]; then
        PARTIAL="$(cut -d 'a' -f 1 <<< $VER)"
    elif [[ $VER == *"b"* ]]; then
        PARTIAL="$(cut -d 'b' -f 1 <<< $VER)"
    elif [[ $VER == *"rc"* ]]; then
        PARTIAL="$(cut -d 'r' -f 1 <<< $VER)"
    else
        PARTIAL=$VER
    fi

    echo "Downloading Python $VER..."
    wget -q https://www.python.org/ftp/python/$PARTIAL/Python-$VER.tgz

    if [[ ! -f Python-$VER.tgz ]]; then
        echo "That Python version does not exist."
        exit 2
    fi

    tar -xf Python-$VER.tgz

    echo "Building Python $VER..."
    cd Python-$VER
    ./configure -q --enable-optimizations --with-ensurepip=install --with-system-ffi
    make -s -j $(nproc)

    echo "Installing Python $VER..."
    sudo make -s altinstall
done

echo "All done!"
