#!/bin/bash

if [[ $# -eq 0 ]]; then
    echo -e "You must provide at least one Python version.\n e.g. sh install-python 3.7.9"
    exit 2
fi

gcc openssl-devel bzip2-devel libffi-devel zlib-devel wget tar make

echo "Configuring packages... This Process may takes upto 10 Minutes or more..."
sudo yum install -q -y \
    wget\
    curl \
    telnet\
    net-tools\
    traceroute\
    tar \
    gcc \
    openssl-devel \
    bzip2-devel \
    libffi-devel \
    zlib-devel \
    make


cd /tmp

for VER do
    if [[ $VER == *"a"* ]]; then
        PARTIAL="$(cut -d 'a' -f 1 <<< $VER)"
    elif [[ $VER == *"b"* ]]; then
        PARTIAL="$(cut -d 'b' -f 1 <<< $VER)"
    elif [[ $VER == *"rc"* ]]; then
        PARTIAL="$(cut -d 'r' -f 1 <<< $VER)"
    else
        PARTIAL=$VER
    fi

    echo "Downloading Python $VER..."
    wget -q https://www.python.org/ftp/python/$PARTIAL/Python-$VER.tgz

    if [[ ! -f Python-$VER.tgz ]]; then
        echo "That Python version does not exist."
        exit 2
    fi

    tar -xf Python-$VER.tgz

    echo "Building Python $VER..."
    cd Python-$VER
    ./configure -q --enable-optimizations --with-ensurepip=install --with-system-ffi
    make -s -j $(nproc)

    echo "Installing Python $VER..."
    sudo make -s altinstall

    echo "Applying PATH for Python $VER..."
    echo -e "alias python=/usr/bin/python$VER\nPATH=$PATH:/usr/local/bin/python$VER" >> ~/.bashrc
    source ~/.bashrc
    
    echo "Check versions of Python and pip"
    python$VER -V
    pip$VER -V
done

# echo -e "alias python=/usr/bin/python3\nPATH=$PATH:/usr/local/bin/python3.8" >> ~/.bashrc
# source ~/.bashrc

echo "All done!"
