#! /bin/bash
##########################################
# Author : Sagar Malla
# Date : 2024-April-05
# Desc : OpenSSL Script
# Version : v1.2
##########################################

set -x

# Unistall OpenSSL
openssl version
sudo yum -q -y remove openssl openssl-devel
sudo yum -q -y remove openssl*
openssl version # to check openssl removed or not

# Installing OpenSSL version 3.1.3
sudo yum -q -y groupinstall "Development Tools"
sudo yum -q -y install perl-IPC-Cmd
cd /tmp
wget https://www.openssl.org/source/openssl-3.1.3.tar.gz
tar xvf openssl-*.tar.gz
cd openssl-*/
./config --prefix=/usr/local/openssl --openssldir=/usr/local/openssl
make -j $(nproc)
sudo make install
sudo ldconfig

# Setup OpenSSL path
sudo tee /etc/profile.d/openssl.sh<<EOF
export PATH=/usr/local/openssl/bin:\$PATH
export LD_LIBRARY_PATH=/usr/local/openssl/lib:/usr/local/openssl/lib64:\$LD_LIBRARY_PATH
EOF

source /etc/profile.d/openssl.sh

logout  # this command will logout the current user from the session
        #now relogin or ssh to the server

which openssl